services:
  catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:CatalogueContext=Data Source=cataloguedb;TrustServerCertificate=True;Initial Catalog=CatalogueContext;User ID=sa;Password=Test@123456" 
    ports:
      - "8080"

  demoapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

