version: '3.4'

networks:
  backend:

services:

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile
    networks:
      - backend
    depends_on:
      - cataloguedb
    environment:
      - DB_HOST=cataloguedb
      - DB_USER=sa
      - DB_PASSWORD=Test@123456

  demoapp:
    image: ${DOCKER_REGISTRY-}demoapp
    build:
      context: .
      dockerfile: DemoApp/Dockerfile
    networks:
      - backend

  cataloguedb:
    container_name: catalogue-DB
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123456
    ports:
      - 18001:1433
    networks:
      - backend